name: Build React App

# Trigger the workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs to run
jobs:
  build:
    # The environment you want to run on (Ubuntu is standard for Node.js apps)
    runs-on: ubuntu-latest

    # Steps to execute the build
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (you can specify the Node version you use)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or whichever Node version you are using

      - name: navigate to the folder
        run: cd portfolio

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build the app
        run: npm run build

      # (Optional) Step 5: Upload the build folder as an artifact
      - name: Upload production-ready build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
