name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Triggers when there's a push to 'master'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd portfolio
          npm install

      # Step 4: Run ESLint with npx
      - name: Run ESLint
        run: |
          cd portfolio
          npx eslint 'src/**/*.{js,jsx}'  # Use npx to run the locally installed ESLint

      # Step 5: Run Prettier (optional) with npx
      - name: Run Prettier
        run: |
          cd portfolio
          npx prettier --write 'src/**/*.{js,jsx}'  # Use npx to run Prettier locally

      # Step 6: Run tests (allow to fail)
      - name: Run tests
        run: |
          cd portfolio
          npm test
        continue-on-error: true  # Allow the pipeline to continue even if tests fail

      # Step 7: Build the app
      - name: Build the app
        run: |
          cd portfolio
          npm run build

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio/portfolio/build
          publish_branch: gh-pages

